name: Windows CI (VS2022)

on: [push, pull_request]

jobs:
  windows-build:
    name: Windows (MSVC)
    runs-on: windows-2022
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg
          cd vcpkg
          .\bootstrap-vcpkg.bat
          .\vcpkg install sdl2

      - name: Setup MSVC
        uses: microsoft/setup-msbuild@v2
        with:
          msbuild-architecture: x64
          vs-version: latest

      - name: Configure CMake
        run: |
          mkdir build
          cd build
          cmake .. `
            -G "Visual Studio 17 2022" `
            -A x64 `
            -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake

      - name: Build
        run: |
          cd build
          cmake --build . --config Release --parallel 4
